allowBuilds:
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  aws-sdk: true
  bcrypt: true
  dd-trace: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
